EasyEngine/site-type-php

src/Site_PHP_Docker.php
=> Modify path constant

src/PHP.php, src/Site_PHP_Docker.php
Depends on https://github.com/EasyEngine/site-command/pull/128
=> Update to accomodate global db

src/PHP.php, src/Site_PHP_Docker.php
Fixes https://github.com/EasyEngine/site-command/issues/126
=> Fix https issue with proper docker-compose gen

src/PHP.php, src/Site_PHP_Docker.php, templates/config/nginx/main.conf.mustache
Depends on EasyEngine/service-command#5
Tests will be failing till it is merged.
Signed-off-by: Riddhesh Sanghvi riddheshsanghvi96@gmail.com
=> Add global-redis and update service call of global services

src/PHP.php
Closes: https://github.com/EasyEngine/site-type-php/issues/19
=> Remove old function call

src/PHP.php
closes:https://github.com/EasyEngine/site-command/issues/125
Depends on:https://github.com/EasyEngine/site-type-wp/pull/57
=> fix curl error on subdomain in site-type-php

src/PHP.php
issue ref: https://github.com/EasyEngine/site-command/issues/146
Depends on: https://github.com/EasyEngine/site-command/pull/156
=> Add database entry for cache_host(php)

src/PHP.php
Issue ref - https://github.com/EasyEngine/site-type-wp/issues/42
=> Fix remote db working.

src/PHP.php
Depends on https://github.com/EasyEngine/site-command/pull/158
Issue ref https://github.com/EasyEngine/site-command/issues/157
=> Add try-catch handling if db user creation fails

src/PHP.php, src/Site_PHP_Docker.php
Issue ref: https://github.com/EasyEngine/site-command/issues/172
=> Update volume mountings

src/PHP.php, src/Site_PHP_Docker.php, templates/config/nginx/main.conf.mustache
issue ref: https://github.com/EasyEngine/easyengine/issues/1237
=> Fix page cache persistent bug(php)

src/PHP.php
Issue ref: https://github.com/EasyEngine/easyengine/issues/1244
Depends on: https://github.com/EasyEngine/site-command/pull/174
=> Add check for max sites limit(php)

src/PHP.php, src/Site_PHP_Docker.php, templates/config/nginx/main.conf.mustache, templates/docker-compose.mustache
Issue ref EasyEngine/site-command#187
Depends on EasyEngine/dockerfiles#40
Depends on EasyEngine/site-command#188
=>  Update docker volume mounting

src/PHP.php, src/Site_PHP_Docker.php, templates/config/nginx/main.conf.mustache
Issue ref https://github.com/EasyEngine/dockerfiles/issues/42
Depends on https://github.com/EasyEngine/site-command/pull/190
Depends on EasyEngine/dockerfiles#43
=> Fix configurations

src/PHP.php
Issue ref: EasyEngine/dockerfiles#42
Depends on: EasyEngine/dockerfiles#46
Signed-off-by: Riddhesh Sanghvi riddheshsanghvi96@gmail.com
=> Update nginx configuration directories

src/PHP.php, src/Site_PHP_Docker.php
=> Add php logs

src/PHP.php, src/Site_PHP_Docker.php, templates/config/nginx/main.conf.mustache
Issue ref: EasyEngine/dockerfiles#51
Depends on EasyEngine/easyengine#1256
Depends on EasyEngine/easyengine#1269
=> Consolidate configuration

src/Site_PHP_Docker.php
Issue ref: https://github.com/EasyEngine/site-command/issues/205
=> Fix nohttps in docker-compose generation

src/PHP.php, src/Site_PHP_Docker.php, templates/config/nginx/main.conf.mustache, templates/docker-compose.mustache, templates/my.cnf.mustache
Issue ref: https://github.com/EasyEngine/easyengine/issues/1059
Depends on: EasyEngine/easyengine#1288
Depends on: EasyEngine/dockerfiles#60
Depends on: EasyEngine/service-command#34
=> Update site-type-php for macOS support

src/PHP.php
Changes related to: https://github.com/EasyEngine/dockerfiles/pull/60
Depends on: https://github.com/EasyEngine/site-command/pull/215
=> Update php.ini path

src/PHP.php
=> Add site root in info

src/Site_PHP_Docker.php, templates/docker-compose.mustache
Issue ref: https://github.com/EasyEngine/site-command/issues/218
=> Fix loopback request to site

src/PHP.php, src/Site_PHP_Docker.php, templates/config/php-fpm/php.ini.mustache
Issue ref: EasyEngine/site-command#223
Depends on: EasyEngine/easyengine#1303
Depends on: EasyEngine/site-command#224
Signed-off-by: Riddhesh Sanghvi riddheshsanghvi96@gmail.com
=> Add support for PHP 5.6

src/PHP.php, src/Site_PHP_Docker.php
=> Fix 5.6 checks

src/PHP.php
Issue ref: https://github.com/EasyEngine/easyengine/issues/1315
=> Fix php reload issue

src/Site_PHP_Docker.php
Issue ref: https://github.com/EasyEngine/site-type-wp/issues/116
=> Fix cache network bridging for rds scenario

src/Site_PHP_Docker.php
Issue ref: EasyEngine/easyengine#1331
=> Fix backend network handling

src/PHP.php
Examples for changes in: https://github.com/EasyEngine/site-command/pull/258
=> Add example for self-signed cert

src/Site_PHP_Docker.php
Issue ref: https://github.com/EasyEngine/easyengine/issues/1346
Depends on: https://github.com/EasyEngine/site-command/pull/265
=> Update setting ssl-policy env variable

src/PHP.php
issue: https://github.com/EasyEngine/site-command/issues/271
=> Add host entry for site create with self SSL

src/PHP.php
Depends on: https://github.com/EasyEngine/site-command/pull/267
=> Add parent site ssl certificate check before site creation

features/site.feature, src/PHP.php, templates/config/nginx/main.conf.mustache
issue: https://github.com/EasyEngine/feature-requests/issues/74
=> Feature: change document root for php site.

features/site.feature, src/PHP.php
issue: https://github.com/EasyEngine/site-command/issues/292
=> Add custom ssl support for php site

src/PHP.php, src/Site_PHP_Docker.php, templates/config/.env.mustache
Issue ref: [EasyEngine/easyengine#1390](https://github.com/EasyEngine/easyengine/issues/1390)
Depends on: [EasyEngine/easyengine#1392](https://github.com/EasyEngine/easyengine/pull/1392)
Depends on: [EasyEngine/service-command#56](https://github.com/EasyEngine/service-command/pull/56)
Signed-off-by: Riddhesh Sanghvi [riddheshsanghvi96@gmail.com](mailto:riddheshsanghvi96@gmail.com)
=> Add env and docker-compose configuration for newrelic

src/PHP.php, src/Site_PHP_Docker.php
Depends on: https://github.com/EasyEngine/easyengine/pull/1407
=> Add support for PHP 7.3

src/PHP.php
=> Add support for php 7.0

src/PHP.php, templates/config/php-fpm/php.ini-56.mustache
Signed-off-by: Riddhesh Sanghvi <riddhesh237@gmail.com>
=> Add ssmtp config for PHP 5.6

src/PHP.php
Signed-off-by: Riddhesh Sanghvi <riddhesh237@gmail.com>
=> Make PHP 7.4 default PHP version

src/PHP.php
Depends on EasyEngine/site-command#337
=> Check alias domains while site creation

src/PHP.php, src/Site_PHP_Docker.php
Depends on https://github.com/EasyEngine/site-command/pull/341
=> Add alias domain support in php site type

src/Site_PHP_Docker.php, templates/docker-compose.mustache
Ref: https://github.com/EasyEngine/feature-requests/issues/88
Signed-off-by: dhsathiya <devarshisathiya5@gmail.com>
=> Add sysctl parameters in site type PHP

src/PHP.php, templates/config/nginx/admin-tools.conf.mustache, templates/config/nginx/main.conf.mustache
Ref: https://github.com/EasyEngine/admin-tools-command/issues/45
Signed-off-by: dhsathiya <devarshisathiya5@gmail.com>
=> Add config for ee-admin

templates/config/nginx/main.conf.mustache
Ref: https://github.com/EasyEngine/site-command/issues/364
=> Disable js css nginx log

src/PHP.php
Depends on https://github.com/EasyEngine/easyengine/pull/1700
=> Update with global compose-exec helper function
